apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thingsboard
  labels:
    k8s-app: thingsboard
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  - configmaps
  - pods
  - pods/status
  - secrets
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
