apiVersion: v1
kind: Service
metadata:
  name: thingsboard
  namespace: thingsboard
  labels:
    k8s-app: thingsboard
spec:
  type: NodePort
  ports:
  - port: 9090
    name: http
    nodePort: 30080
  - port: 1883
    name: mqtt
    nodePort: 31883
  - port: 5683
    name: coap
    nodePort: 31683
  selector:
    k8s-app: thingsboard
